
MAKEFILE	:=

TARGET		:= test

NVERSION	:= 1

INCLUDES	:= -I. -I.. 


LIBS		:= -lACE 

CFLAGS		:= $(CFLAGS_PASS)
DCFLAGS		:= $(DCFLAGS_PASS)
LDFLAGS		:= $(LDFLAGS_PASS)
DLDFLAGS	:= $(DLDFLAGS_PASS)


CC		:= cc
CXX		:= c++
CPP		:= cpp
LD		:= $(CC) 

